describe("calendar select", () => {
    it("event appear and disapear when click on the select calendar", () => {
        cy.login();
        cy.addBlankEvent();
        cy.wait(500);
        cy.get(".today-num-bubble").as("bubble");
        cy.get("@bubble").parent().parent().as("dayCard");
        cy.wait(500);
        cy.get("@dayCard").should("contain", "test event");
        cy.get(".check-container").click();
        cy.get("@dayCard").should("not.contain", "test event");
        cy.get(".check-container").click();
        cy.deleteEvent();
    });
    it("adding, editing and deleting a calendar work", () => {
        cy.login();
        cy.get("#calendar-add").click();
        cy.wait(500);
        cy.get(".input-open").type("test calendar");
        cy.get(".calendar-add-div > .button-full").click();
        cy.get(".calendar-select").should("contain", "test calendar");
        cy.get(".calendar-select").trigger("mouseover", "center");
        cy.get(".fa-pen").click();
        cy.get(".input-open").clear().type("test calendar edited");
        cy.get(".cal-edit-btns > .button-full").click();
        cy.get(".calendar-select").should("contain", "test calendar edited");
        cy.get(".fa-trash").click();
        cy.get(".last-button").click();
        cy.get(".calendar-select").should("not.contain", "test calendar edited");
    });
    it("delete popup show up the right number of events", () => {
        cy.login();
        cy.addBlankEvent();
        cy.get(".fa-trash").click();
        cy.get(".last-button").click();
        cy.addBlankEvent();
        cy.addBlankEvent();
        cy.get(".fa-trash").click();
        cy.get(".calendar-delete-popup > p").should("contain", "Are you sure to delete Default Calendar? It will destroy every event inside of it! (It has 2 events !)");
        cy.get(".last-button").click();
        cy.wait(10);
        cy.get("#calendar-add").as("calendarAdd");
        cy.wait(500);
        cy.get("@calendarAdd").click();
        cy.get(".input-open").type("test calendar");
        cy.get(".calendar-add-div > .button-full").click();
        cy.addBlankEvent();
        cy.addBlankEvent();
        cy.get(".fa-trash").click();
        cy.get(".calendar-delete-popup > p").should("contain", "Are you sure to delete test calendar? It will destroy every event inside of it! (It has 2 events !)");
        cy.get(".last-button").click();
    });
});
